version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/codedeploy-artifacts

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root