services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RAWG_API_KEY=${RAWG_API_KEY}
      - RAPID_API_KEY=${RAPID_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules

    command: sh -c "npm run build && npm start"

# //run docker compose up if file is edited.