services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RAWG_API_KEY=${RAWG_API_KEY}
      - RAPID_API_KEY=${RAPID_API_KEY}
      - NEXT_PUBLIC_RAWG_API_KEY=${NEXT_PUBLIC_RAWG_API_KEY}
      - NODE_ENV=production
    restart: on-failure

# //run docker compose up --build if file is edited.



